# Site Settings
encoding                 : "utf-8"
locale                   : "en"
title                    : "Vishwa"
title_separator          : "-"
description              : ""
favicon                  : "/assets/images/favicon.png"
logo                     : "/assets/images/favicon.png"
lang                     : 'en_US'
avatar                   : false
url                      : "https://v1shwa.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog" leave blank if no subpath
tag_page_layout          : tag_index
tag_page_dir             : tag

# Site Author
author:
  name                   : "Vishwa" # appears in the footer and atom feed

comments                 : true # set it to false to disable comments
disqus:
  shortname              : "vishwa" # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-

atom_feed:
  path                   : "/feed.xml"

og_image                 : "" # Open Graph/Twitter default site image, optional for seo and social sharing

# Social sharing
twitter:
  username               : "v1shwa" # optional, for social sharing

github:
  username               : "v1shwa"

# Analytics
analytics:
  google:
    tracking_id          : "UA-71763469-3" # add your google tracking id here

# Reading Files
include:
  - _pages
# Files excluded from Jekyll builds
exclude:
- Gemfile
- Gemfile.lock
- TODO


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false # true will re-build only pages that have changed. Could break the site.


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /blog/:title/
paginate: 5 # amount of posts to show
paginate_path: "/blog/page:num/"
timezone: "Asia/Kolkata" # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

collections:
  projects:
    output: true
    permalink: /:collection/:title/

# Plugins
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-feed


# Jekyll Stuff
source: .
destination: _site

# Front matter defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      comments: false
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: page
      share: false